### ISSUE TITLE
Cannot install yoctolib using npm

### ISSUE THREAD

**Issue by Reddhi** [yoctopuce/yoctolib_es2017#1]
From Console:
```
C:\Users\itgadmin\Documents\YoctoDemo>npm i yoctolib-es2017
npm ERR! code ETARGET
npm ERR! notarget No matching version found for yoctolib-es2017@^1.10.31701
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\itgadmin\AppData\Roaming\npm-cache\_logs\2018-08-20T07_44_09_707Z-debug.log
```

Debug Log File Contents:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'yoctolib-es2017' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose npm-session eb787f6b955a3edf
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/yoctolib-es2017 15ms (from cache)
8 silly registry:manifest no matching version for yoctolib-es2017@^1.10.31701 in the cache. Forcing revalidation
9 http fetch GET 304 https://registry.npmjs.org/yoctolib-es2017 239ms (from cache)
10 silly fetchPackageMetaData error for yoctolib-es2017@^1.10.31701 No matching version found for yoctolib-es2017@^1.10.31701
11 verbose type range
12 verbose stack yoctolib-es2017: No matching version found for yoctolib-es2017@^1.10.31701
12 verbose stack     at pickManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\npm-pick-manifest\index.js:65:11)
12 verbose stack     at fetchPackument.then.packument (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:52:18)
12 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
12 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
12 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
12 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
12 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
12 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
12 verbose stack     at runCallback (timers.js:810:20)
12 verbose stack     at tryOnImmediate (timers.js:768:5)
12 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
13 verbose cwd C:\Users\itgadmin\Documents\YoctoDemo
14 verbose Windows_NT 10.0.17134
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "yoctolib-es2017"
16 verbose node v8.11.3
17 verbose npm  v5.6.0
18 error code ETARGET
19 error notarget No matching version found for yoctolib-es2017@^1.10.31701
20 error notarget In most cases you or one of your dependencies are requesting
20 error notarget a package version that doesn't exist.
21 verbose exit [ 1, true ]
```

**Comment by Reddhi** [comment]
The issue is with the package.json.

**The repository version:**
 ```
 "dependencies": {
    "ws": "^1.0.1",
    "yoctolib-es2017": "^1.10.31701"
  }
```

**Correct Version**
```
  "dependencies": {
    "ws": "^1.0.1",
    "yoctolib-es2017": "^1.10.30813"
  }
```
The Yoctolib version needs to be changed.

**Comment by yoctopuce** [comment]
Hi,

I'm very sorry for this inconvenient. The publish of our last npm package
failed and we did not spot this error sooner. We have uploaded it again,
and everything is now available.

Your npm command 'npm i yoctolib-es2017' should work as expected.

Thank you for reporting this error.

Best regards

Sébastien Rinsoz

**Comment by Reddhi** [comment]
Can I use "yoctolib-es2017": "^1.10.31701" now?

**Comment by yoctopuce** [comment]
Yes.
